USE TaskManagementDB;

CREATE TABLE User (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);
